name: DemoPipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        shell: bash
      - name: Terraform Validate
        run: terraform validate
        shell: bash

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        shell: bash

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan
      #   shell: bash 
