name: DemoPipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"
          
  
