name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform init
        uses: comu2e/tfnotify-composite-action@1.0.4

      - name: terraform-plan
        uses: dflook/terraform-plan@v1.29.1
